name: Deploy to VPS

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Navigate to the correct app directory on your VPS
            cd /opt/ATWARBSS-main
            
            # Pull the latest code
            git pull
            
            # Install any new dependencies
            npm install
            
            # Build the React app
            npm run build
            
            # Restart the PM2 API process
            pm2 restart atwar-api
